name: PR / Label

on:
  pull_request_target: { }

jobs:
  triage:
    name: Triage
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Apply context labels
      uses: actions/labeler@v5
      with:
        configuration-path: .github/labeler.yaml
        sync-labels: true
    - name: Apply commit message labels
      uses: actions/github-script@v7
      with:
        script: |
          const labels = []
          if (context.payload.pull_request.title.startsWith('fix:')) {
            labels.push('bug ðŸ›')
          }
          if (context.payload.pull_request.title.startsWith('chore:')) {
            labels.push('chore ðŸ§¹')
          }
          if (context.payload.pull_request.title.startsWith('feat:')) {
            labels.push('feature ðŸ’¡')
          }
          if (labels.length > 0) {
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              labels,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
          }
